service: sample-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: https://sxgtr83iji.execute-api.us-east-1.amazonaws.com/dev/
          method: ANY
          cors: true
      - http: 
          path: https://sxgtr83iji.execute-api.us-east-1.amazonaws.com/dev/{proxy+}
          method: ANY
          cors: true